// Textos de receitas, refeições e cardápios do plano alimentar.

export const tReceitas = {
  titulo: 'Receitas',
  nova: 'Nova receita',
  vazio: 'Nenhuma receita ainda.',
  colunas: ['Receita', 'Porções', 'kcal por porção', 'Status'],
  publicadas: 'Receitas publicadas',
  rascunhos: 'Em rascunho',
  filtroTag: 'Tag',
  campoNome: 'Nome da receita',
  foto: 'Foto',
  trocarFoto: 'Trocar foto',
  escolherFoto: 'Escolher foto',
  ingredientes: 'Ingredientes',
  preparo: 'Modo de preparo',
  porcoes: 'Rendimento (porções)',
  tags: 'Tags',
  tagsAjuda: 'Separe por vírgula',
  tempo: 'Tempo de preparo (min)',
  refeicoes: 'Serve para',
  objetivos: 'Temas',
  calcular: 'Calcular pelos alimentos cadastrados',
  itens: 'Ingredientes calculados',
  porPorcao: 'Por porção',
  removida: 'Receita removida',
  negrito: 'Negrito',
  lista: 'Lista com marcadores',
  listaNumerada: 'Lista numerada',
}

export const tRefeicoes = {
  titulo: 'Refeições',
  nova: 'Nova refeição',
  editar: 'Editar refeição',
  vazio: 'Nenhuma refeição modelo ainda.',
  colunas: ['Refeição', 'Tipo', 'Energia', ''],
  total: 'Refeições modelo',
  filtroTipo: 'Tipo',
  campoDescricao: 'Descrição',
  campoTipo: 'Tipo',
  campoHorario: 'Horário sugerido',
  alimentos: 'Alimentos selecionados',
  semAlimentos: 'Nenhum alimento ainda.',
  adicionarAlimento: 'Adicionar alimento',
  adicionarOu: 'Adicionar opção "ou"',
  ou: 'ou',
  removerItem: (n: string) => `Remover ${n}`,
  observacao: 'Observação',
  salvarContinuar: 'Salvar e continuar',
  salvarFechar: 'Salvar e fechar',
  texto: 'Texto da refeição',
}

export const tEscolher = {
  titulo: 'Adicionar alimento',
  tituloOu: 'Adicionar opção "ou"',
  fontes: { todas: 'Todas', taco: 'TACO', proprio: 'Meus alimentos', receitas: 'Receitas' },
  receita: 'Receita',
  medida: 'Medida caseira',
  gramas: 'gramas',
  porcao: 'porção',
  quantidade: 'Quantidade',
  adicionar: 'Adicionar',
  escolher: 'Escolha um item da lista',
}

export const tCardapios = {
  titulo: 'Cardápios',
  novo: 'Novo cardápio',
  vazio: 'Nenhum cardápio ainda.',
  colunas: ['Cardápio', 'Objetivo', 'Refeições', 'Energia', 'Status'],
  publicados: 'Cardápios publicados',
  rascunhos: 'Em rascunho',
  filtroObjetivo: 'Objetivo',
  campoNome: 'Nome do cardápio',
  campoObjetivo: 'Objetivo',
  campoModelo: 'Modelo do plano',
  modelos: { calculado: 'Alimentos calculados', texto: 'Texto livre' },
  refeicoes: 'Refeições',
  adicionarRefeicao: 'Adicionar nova refeição',
  carregarModelo: 'Carregar refeição modelo',
  semRefeicoes: 'Nenhuma refeição ainda.',
  duplicarRefeicao: (n: string) => `Duplicar ${n}`,
  editarRefeicao: (n: string) => `Editar ${n}`,
  removerRefeicao: (n: string) => `Remover ${n}`,
  substitutas: (n: number) => (n === 1 ? 'Exibir 1 substituição' : `Exibir ${n} substituições`),
  ocultarSubstitutas: 'Ocultar substituições',
  adicionarSubstituta: 'Adicionar substituição',
  substituta: 'Substituição',
  carregarSalvo: 'Carregar cardápio salvo',
  carregarAviso: 'As refeições do cardápio escolhido substituem as atuais.',
  visualizarAluna: 'Visualizar como aluna',
  pdf: 'Gerar PDF',
  resumo: 'Resumo de nutrientes',
  totalDia: 'Total do dia',
  porRefeicao: 'Por refeição',
  listaCompras: 'Lista de compras',
  gerarLista: 'Gerar a partir do cardápio',
  listaVazia: 'Gere a lista a partir dos alimentos do cardápio.',
  semana: 'Quantidades para 7 dias',
  novoItemLista: 'Adicionar item',
  item: 'Item',
  quantidade: 'Quantidade',
  naoSalvo: 'Alterações não salvas',
  copia: (n: string) => `${n} (cópia)`,
  observacao: 'Observação',
}
