// Textos de Minha evolução (medidas). Os componentes só leem daqui.

export const textos = {
  carregando: 'Carregando',
  erro: 'Não foi possível carregar.',
  erroSalvar: 'Não deu certo agora. Tente de novo.',
  tentar: 'Tentar de novo',
  cancelar: 'Cancelar',
  salvar: 'Salvar',
  salvando: 'Salvando',
  evolucao: {
    titulo: 'Minha evolução',
    privado: 'Só você e as profissionais veem.',
    novo: 'Registrar medidas',
    janela: 'Novo registro',
    vazio: 'Registre suas medidas para acompanhar a sua evolução.',
    grafico: (campo: string) => `Evolução de ${campo}`,
    poucos: 'Com dois registros a linha da evolução aparece aqui.',
    data: 'Data',
    foto: 'Foto (opcional)',
    escolherFoto: 'Tirar ou escolher foto',
    trocarFoto: 'Trocar foto',
    fotoDoDia: (d: string) => `Foto de ${d}`,
    apagar: 'Apagar',
    apagarRotulo: (d: string) => `Apagar o registro de ${d}`,
    confirmar: 'Apagar este registro?',
    sim: 'Sim, apagar',
    nao: 'Manter',
    peloMenosUm: 'Preencha pelo menos uma medida.',
    invalido: (campo: string) => `Confira ${campo}.`,
    dataInvalida: 'Escolha uma data até hoje.',
    abasRotulo: 'Medida do gráfico',
  },
  campos: {
    peso: { nome: 'Peso', unidade: 'kg' },
    cintura: { nome: 'Cintura', unidade: 'cm' },
    quadril: { nome: 'Quadril', unidade: 'cm' },
    braco: { nome: 'Braço', unidade: 'cm' },
    coxa: { nome: 'Coxa', unidade: 'cm' },
  },
}
