// Textos dos módulos novos do painel (cardápios, desafios, alunas, configurações e os que ainda não ligaram).

export const desafios = {
  titulo: 'Desafios e prêmios',
  pagina: 'Desafios e prêmios',
  novo: 'Novo desafio',
  editar: 'Editar desafio',
  vazio: 'Nenhum desafio ainda.',
  coluna: 'Desafio',
  colunaPeriodo: 'Período',
  colunaGente: 'Participantes',
  periodo: (inicio: string, fim: string) => `${inicio} a ${fim}`,
  ativos: 'Desafios ativos',
  participando: 'Alunas participando',
  proximo: (nome: string) => `Próximo a encerrar · ${nome}`,
  nenhum: 'Nenhum',
  semProximo: 'Próximo a encerrar',
  situacao: { rascunho: 'Rascunho', agendado: 'Agendado', ativo: 'Ativo', encerrado: 'Encerrado' },
  tipos: { sim_nao: 'Sim ou não', foto: 'Foto', numero: 'Número' },
  publicos: { todas: 'Todas as alunas', inscritas: 'Só quem entrar no desafio' },
  campoNome: 'Nome do desafio',
  campoDescricao: 'Descrição',
  campoInicio: 'Começa em',
  campoFim: 'Termina em',
  campoTipo: 'Tipo de check-in',
  campoUnidade: 'Unidade (copos, minutos)',
  campoMetaDiaria: 'Meta por dia',
  campoMetaDias: 'Dias de check-in para concluir',
  campoPontos: 'Pontos por dia',
  campoBonus: 'Bônus ao concluir',
  campoPremio: 'Prêmio',
  campoPublico: 'Vale para',
  dadoPeriodo: 'Período',
  dadoMeta: 'Meta',
  meta: (dias: number, diaria?: string) => `${dias} dias${diaria ? `, ${diaria} por dia` : ''}`,
  dadoPontos: 'Pontos',
  pontos: (dia: number, bonus: number) => `${dia} por dia, +${bonus} ao concluir`,
  dadoPremio: 'Prêmio',
  dadoGente: 'Participando',
  dadoConcluiram: 'Concluíram',
  encerrar: 'Encerrar desafio',
  vencedoras: 'Vencedoras',
  semVencedoras: 'Nenhuma aluna concluiu este desafio.',
  dias: (n: number) => `${n} dias`,
  progresso: 'Andamento',
  andamento: (dia: number, total: number, faltam: number) =>
    faltam === 0
      ? `Dia ${dia} de ${total} · último dia`
      : `Dia ${dia} de ${total} · faltam ${faltam} dias`,
  comeca: (data: string) => `Começa em ${data}`,
  erros: {
    periodo: 'O fim não pode ser antes do início',
    metaDias: 'A meta não pode passar dos dias do desafio',
    numero: 'Preencha a unidade e a meta por dia',
    inteiro: 'Use um número inteiro',
    data: 'Escolha a data',
  },
}

export const alunas = {
  titulo: 'Alunas',
  pagina: 'Alunas da HORA',
  vazio: 'Nenhuma aluna ainda.',
  colunas: ['Aluna', 'Apelido', 'Início', 'Dia', 'Último acesso', 'Status'],
  ativas: 'Alunas ativas',
  hoje: 'Entraram hoje',
  atencao: 'Precisam de atenção',
  status: { em_dia: 'Em dia', atencao: 'Atenção', sumiu: 'Sumiu', sem_acesso: 'Sem acesso' },
  nunca: 'Ainda não entrou',
  diaN: (n: number) => `Dia ${n}`,
  dadoApelido: 'Apelido',
  dadoInicio: 'Início do acesso',
  dadoFim: 'Fim do acesso',
  dadoDia: 'Dia',
  dadoUltimo: 'Último acesso',
  dadoStatus: 'Status',
  progresso: 'Progresso nas aulas',
  aulas: (feitas: number, liberadas: number) =>
    liberadas - feitas > 0
      ? `${feitas} de ${liberadas} aulas liberadas · faltam ${liberadas - feitas}`
      : `${feitas} de ${liberadas} aulas liberadas`,
}

export const configuracoes = {
  titulo: 'Configurações',
  pagina: 'Configurações',
  colunas: ['Item', 'Valor atual'],
  pixCheio: 'Pix, preço cheio',
  pixOferta: 'Pix na oferta do ORA',
  diaOferta: 'Oferta do ORA',
  itens: {
    precos: 'Preços dos planos',
    oferta: 'Oferta do ORA',
    termos: 'Termos de uso',
    privacidade: 'Política de privacidade',
  },
  secoes: (n: number) => (n === 1 ? '1 seção' : `${n} seções`),
  cheio: 'Preço cheio',
  oferta: 'Na oferta do ORA',
  pix: 'Pix à vista',
  parcelado: 'Parcela do parcelado (12x)',
  recorrente: 'Parcela do mensal (12x)',
  inicio: 'Começa em',
  fim: 'Termina em',
  secaoTitulo: 'Título da seção',
  secaoTexto: 'Texto',
  novaSecao: 'Adicionar seção',
  removerSecao: (n: number) => `Remover a seção ${n}`,
  remover: 'Remover',
  atualizado: (data: string) => `Atualizado em ${data}`,
  erros: { valor: 'Informe um valor', fim: 'O fim tem que ser depois do início' },
}
