// Textos dos módulos novos do painel (cardápios, desafios, alunas, configurações e os que ainda não ligaram).

export const cardapios = {
  titulo: 'Cardápios',
  pagina: 'Cardápios da comunidade',
  novo: 'Novo cardápio',
  vazio: 'Nenhum cardápio ainda.',
  coluna: 'Cardápio',
  colunaRefeicoes: 'Refeições',
  refeicoes: (n: number) => `${n} de 6`,
  publicados: 'Cardápios publicados',
  rascunhos: 'Em rascunho',
  campoObjetivo: 'Objetivo',
  objetivos: ['Emagrecimento', 'Ganho de massa', 'Manutenção', 'Mais energia'],
  campoTitulo: 'Título',
  campoDescricao: 'Descrição',
  cafe: 'Café da manhã',
  lancheManha: 'Lanche da manhã',
  almoco: 'Almoço',
  lancheTarde: 'Lanche da tarde',
  jantar: 'Jantar',
  ceia: 'Ceia',
  listaCompras: 'Lista de compras',
}

export const desafios = {
  titulo: 'Desafios e prêmios',
  pagina: 'Desafios e prêmios',
  novo: 'Novo desafio',
  vazio: 'Nenhum desafio ainda.',
  coluna: 'Desafio',
  colunaPeriodo: 'Período',
  colunaGente: 'Participantes',
  periodo: (inicio: string, fim: string) => `${inicio} a ${fim}`,
  ativos: 'Desafios ativos',
  participando: 'Alunas participando',
  proximo: (nome: string) => `Próximo a encerrar · ${nome}`,
  nenhum: 'Nenhum',
  semProximo: 'Próximo a encerrar',
  situacao: { rascunho: 'Rascunho', agendado: 'Agendado', ativo: 'Ativo', encerrado: 'Encerrado' },
  tipos: { sim_nao: 'Sim ou não', foto: 'Foto', numero: 'Número' },
  publicos: { todas: 'Todas as alunas', inscritas: 'Só quem entrar no desafio' },
  campoNome: 'Nome do desafio',
  campoDescricao: 'Descrição',
  campoInicio: 'Começa em',
  campoFim: 'Termina em',
  campoTipo: 'Tipo de check-in',
  campoUnidade: 'Unidade (copos, minutos)',
  campoMetaDiaria: 'Meta por dia',
  campoMetaDias: 'Dias de check-in para concluir',
  campoPontos: 'Pontos por dia',
  campoBonus: 'Bônus ao concluir',
  campoPremio: 'Prêmio',
  campoPublico: 'Vale para',
  dadoPeriodo: 'Período',
  dadoMeta: 'Meta',
  meta: (dias: number, diaria?: string) => `${dias} dias${diaria ? `, ${diaria} por dia` : ''}`,
  dadoPontos: 'Pontos',
  pontos: (dia: number, bonus: number) => `${dia} por dia, +${bonus} ao concluir`,
  dadoPremio: 'Prêmio',
  dadoGente: 'Participando',
  dadoConcluiram: 'Concluíram',
  encerrar: 'Encerrar desafio',
  vencedoras: 'Vencedoras',
  semVencedoras: 'Nenhuma aluna concluiu este desafio.',
  dias: (n: number) => `${n} dias`,
  erros: {
    periodo: 'O fim não pode ser antes do início',
    metaDias: 'A meta não pode passar dos dias do desafio',
    numero: 'Preencha a unidade e a meta por dia',
    inteiro: 'Use um número inteiro',
    data: 'Escolha a data',
  },
}

export const alunas = {
  titulo: 'Alunas',
  pagina: 'Alunas da HORA',
  vazio: 'Nenhuma aluna ainda.',
  colunas: ['Aluna', 'Apelido', 'Início', 'Dia', 'Último acesso', 'Status'],
  ativas: 'Alunas ativas',
  hoje: 'Entraram hoje',
  atencao: 'Precisam de atenção',
  status: { em_dia: 'Em dia', atencao: 'Atenção', sumiu: 'Sumiu', sem_acesso: 'Sem acesso' },
  nunca: 'Ainda não entrou',
  diaN: (n: number) => `Dia ${n}`,
  dadoApelido: 'Apelido',
  dadoInicio: 'Início do acesso',
  dadoFim: 'Fim do acesso',
  dadoDia: 'Dia',
  dadoUltimo: 'Último acesso',
  dadoStatus: 'Status',
  progresso: 'Progresso nas aulas',
  aulas: (feitas: number, liberadas: number) => `${feitas} de ${liberadas} aulas liberadas`,
}

export const configuracoes = {
  titulo: 'Configurações',
  pagina: 'Configurações',
  colunas: ['Item', 'Valor atual'],
  pixCheio: 'Pix, preço cheio',
  pixOferta: 'Pix na oferta do ORA',
  diaOferta: 'Oferta do ORA',
  itens: {
    precos: 'Preços dos planos',
    oferta: 'Oferta do ORA',
    termos: 'Termos de uso',
    privacidade: 'Política de privacidade',
  },
  secoes: (n: number) => (n === 1 ? '1 seção' : `${n} seções`),
  cheio: 'Preço cheio',
  oferta: 'Na oferta do ORA',
  pix: 'Pix à vista',
  parcelado: 'Parcela do parcelado (12x)',
  recorrente: 'Parcela do mensal (12x)',
  inicio: 'Começa em',
  fim: 'Termina em',
  secaoTitulo: 'Título da seção',
  secaoTexto: 'Texto',
  novaSecao: 'Adicionar seção',
  removerSecao: (n: number) => `Remover a seção ${n}`,
  remover: 'Remover',
  salvo: 'Salvo',
  erros: { valor: 'Informe um valor', fim: 'O fim tem que ser depois do início' },
}

export const vazios = {
  mensagem: 'Nenhum registro ainda',
  pontos: {
    titulo: 'Pontos e indicações',
    numeros: ['Pontos dados hoje', 'Indicações no mês', 'Indicações que compraram'],
    colunas: ['Aluna', 'Ação', 'Pontos', 'Quando'],
  },
  forum: {
    titulo: 'Fórum',
    numeros: ['Dúvidas abertas', 'Respondidas na semana', 'Passaram de 72 h'],
    colunas: ['Dúvida', 'Aula', 'Aluna', 'Status'],
  },
  financeiro: {
    titulo: 'Financeiro',
    numeros: ['Vendas no mês', 'Receita do mês', 'Reembolsos'],
    colunas: ['Aluna', 'Plano', 'Valor', 'Status'],
  },
  loja: {
    titulo: 'Loja',
    numeros: ['Produtos', 'Pedidos no mês', 'Resgates com pontos'],
    colunas: ['Produto', 'Preço', 'Estoque', 'Status'],
  },
}
