// Textos do módulo Loja do painel. Os componentes só leem daqui.

export const t = {
  titulo: 'Loja',
  cartoes: {
    publicados: 'Produtos publicados',
    parceiros: 'Parceiros ativos',
    cliques: 'Cliques no mês',
    maisClicado: (nome: string | null) =>
      nome ? `Cliques no mais clicado: ${nome}` : 'Nenhum clique no mês',
  },
  abas: { produtos: 'Produtos', parceiros: 'Parceiros' },
  novoProduto: 'Novo produto',
  novoParceiro: 'Novo parceiro',
  colunasProdutos: ['Produto', 'Parceiro', 'Preço', 'Com desconto', 'Categoria', 'Situação'],
  colunasParceiros: ['Parceiro', 'Cupom geral', 'Contato', 'Produtos', 'Situação'],
  publicado: 'Publicado',
  rascunho: 'Rascunho',
  ativo: 'Ativo',
  inativo: 'Inativo',
  destaque: 'Destaque',
  vazioProdutos: 'Nenhum produto cadastrado.',
  vazioParceiros: 'Nenhum parceiro cadastrado.',
  editar: 'Editar',
  cliquesSemana: 'Cliques por semana',
  semCliques: 'Nenhum clique nas últimas 8 semanas.',
  dados: {
    parceiro: 'Parceiro',
    categoria: 'Categoria',
    preco: 'Preço',
    final: 'Com desconto',
    cupom: 'Cupom',
    link: 'Link de compra',
    situacao: 'Situação',
  },
  produto: {
    novo: 'Novo produto',
    editar: (n: string) => `Editar: ${n}`,
    foto: 'Foto',
    escolherFoto: 'Escolher foto',
    nome: 'Nome',
    parceiro: 'Parceiro',
    categoria: 'Categoria',
    descricao: 'Descrição',
    preco: 'Preço',
    modo: 'Desconto',
    modos: { pct: 'Em %', final: 'Preço final' },
    pct: 'Desconto (%)',
    final: 'Preço com desconto',
    resultado: (pct: number, final: string) => `${pct}% de desconto · ${final}`,
    cupom: 'Cupom do produto (se for diferente do geral)',
    link: 'Link de compra',
    destaque: 'Destaque (aparece primeiro para a aluna)',
    publicado: 'Publicado',
  },
  parceiro: {
    novo: 'Novo parceiro',
    editar: (n: string) => `Editar: ${n}`,
    logo: 'Logo',
    nome: 'Nome',
    descricao: 'Descrição curta',
    cupom: 'Cupom geral (opcional)',
    whatsapp: 'WhatsApp',
    site: 'Site',
    ativo: 'Ativo (aparece para as alunas)',
  },
  erros: {
    nome: 'Escreva o nome',
    parceiro: 'Escolha o parceiro',
    preco: 'Informe o preço',
    final: 'O preço com desconto não pode passar do preço',
    link: 'Use um link que comece com https://',
    whatsapp: 'Confira o WhatsApp com DDD',
    foto: 'Use uma foto JPG, PNG ou WEBP de até 10 MB',
    salvar: 'Não foi possível salvar. Tente de novo.',
  },
  fechar: 'Fechar',
}
