// Textos do painel das profissionais. Os componentes só leem daqui.

import { alunas, configuracoes, desafios } from './textos/modulos'
import { vazios } from './textos/vazios'

export const textos = {
  painel: 'Painel',
  sair: 'Ir para a área da aluna',
  logadaComo: 'Logada como',
  menu: 'Abrir menu',
  fecharMenu: 'Fechar menu',
  status: 'Status',
  ordem: 'Ordem',
  abas: {
    conteudo: 'Conteúdo',
    plano: 'Plano alimentar',
    cardapios: 'Cardápios',
    refeicoes: 'Refeições',
    receitas: 'Receitas',
    alimentos: 'Alimentos',
    lives: 'Lives',
    desafios: 'Desafios e prêmios',
    pontos: 'Pontos e indicações',
    forum: 'Fórum',
    avisos: 'Avisos',
    alunas: 'Alunas',
    financeiro: 'Financeiro',
    loja: 'Loja',
    configuracoes: 'Configurações',
  },
  desafios,
  alunas,
  configuracoes,
  vazios,
  carregando: 'Carregando',
  erro: 'Não foi possível carregar. Tente de novo.',
  tentar: 'Tentar de novo',
  salvar: 'Salvar',
  salvando: 'Salvando',
  salvo: 'Salvo',
  erroSalvar: 'Não foi possível salvar. Tente de novo.',
  cancelar: 'Cancelar',
  fechar: 'Fechar',
  voltar: 'Voltar',
  publicado: 'Publicado',
  rascunho: 'Rascunho',
  publicar: 'Publicar',
  despublicar: 'Tirar do ar',
  subir: 'Subir',
  descer: 'Descer',
  editar: 'Editar',
  temas: {
    titulo: 'Temas',
    pagina: 'Conteúdo da comunidade',
    coluna: 'Tema',
    publicados: 'Temas publicados',
    aulasPublicadas: 'Aulas publicadas',
    aulasRascunho: 'Aulas em rascunho',
    novo: 'Novo tema',
    comece: 'Comece por aqui',
    comeceJanela: 'Comece por aqui (dia 1)',
    comeceVideo: 'Link do vídeo de boas-vindas',
    comeceTexto: 'Texto de boas-vindas',
    comeceAjuda: 'Aparece no topo da Trilha da aluna até ela completar os 5 passos.',
    editar: 'Editar tema',
    vazio: 'Nenhum tema ainda.',
    campoTitulo: 'Nome do tema',
    campoDescricao: 'Frase para a aluna (aparece na escolha do tema)',
  },
  etapas: {
    titulo: 'Etapas',
    nova: 'Nova etapa',
    editar: 'Editar etapa',
    vazio: 'Nenhuma etapa neste tema.',
    campoTitulo: 'Nome da etapa',
    campoDescricao: 'Descrição',
  },
  aulas: {
    titulo: 'Aulas',
    nova: 'Nova aula',
    editar: 'Editar aula',
    vazio: 'Nenhuma aula nesta etapa.',
    campoTitulo: 'Título da aula',
    campoDescricao: 'Descrição',
    campoVideo: 'Link do vídeo',
    exemploVideo: 'Cole o link do vídeo',
    semPrevia: 'Não foi possível mostrar a prévia desse link.',
    campoMaterial: 'Link do material (opcional)',
    campoProfissional: 'Profissional (opcional)',
    exemploProfissional: 'Ana, Clara ou Laís',
    campoDuracao: 'Duração em minutos (opcional)',
    campoDiaPreparacao: 'Dia da preparação (1 a 7)',
    campoDiaEtapa: 'Dia da etapa em que libera',
    ajudaPreparacao: 'Uma aula por dia: o dia 1 é o dia da compra.',
    ajudaEtapa: 'Dia 1 é o dia em que a etapa começa para a aluna.',
    dia: (n: number) => `Dia ${n}`,
  },
  lives: {
    titulo: 'Lives',
    pagina: 'Lives da comunidade',
    coluna: 'Live',
    colunaData: 'Data',
    proxima: 'Próxima live',
    nenhuma: 'Nenhuma',
    agendadas: 'Lives agendadas',
    convidada: 'Convidada',
    link: 'Link da live',
    gravacao: 'Gravação',
    nova: 'Nova live',
    editar: 'Editar live',
    vazio: 'Nenhuma live ainda.',
    campoTema: 'Título da live',
    campoProfissional: 'Profissional',
    semProfissional: 'Escolha',
    campoDuracao: 'Duração em minutos',
    nomes: { ana: 'Ana Milhomem', clara: 'Dra. Clara Maria', lais: 'Laís Moraes' },
    minutos: (n: number) => `${n} min`,
    campoData: 'Data e hora',
    campoConvidada: 'Convidada (opcional)',
    campoLink: 'Link da sala (opcional)',
    campoGravacao: 'Link da gravação (opcional)',
    campoCapa: 'Link da imagem de capa da gravação (opcional)',
    capa: 'Capa da gravação',
  },
  avisos: {
    titulo: 'Avisos',
    pagina: 'Avisos da comunidade',
    coluna: 'Aviso',
    colunaData: 'Aparece em',
    ativos: 'Avisos ativos',
    novo: 'Novo aviso',
    editar: 'Editar aviso',
    vazio: 'Nenhum aviso ainda.',
    campoTitulo: 'Título',
    campoTexto: 'Texto',
    campoPublicarEm: 'Aparece a partir de',
  },
  erros: {
    titulo: 'Escreva o título',
    link: 'Use um link que comece com https://',
    data: 'Escolha a data e a hora',
    dia: 'Use um dia válido (na preparação, de 1 a 7)',
    duracaoLive: 'Use de 15 a 300 minutos',
    texto: 'Escreva o texto',
    duracao: 'Use minutos inteiros, de 1 a 999',
  },
}
