// Textos do painel das profissionais. Os componentes só leem daqui.

export const textos = {
  painel: 'Painel',
  marca: 'HORA',
  sair: 'Ir para a área da aluna',
  logadaComo: 'Logada como',
  menu: 'Abrir menu',
  fecharMenu: 'Fechar menu',
  status: 'Status',
  ordem: 'Ordem',
  abas: { conteudo: 'Conteúdo', lives: 'Lives', avisos: 'Avisos' },
  carregando: 'Carregando',
  erro: 'Não foi possível carregar. Tente de novo.',
  tentar: 'Tentar de novo',
  salvar: 'Salvar',
  salvando: 'Salvando',
  salvo: 'Salvo',
  erroSalvar: 'Não foi possível salvar. Tente de novo.',
  cancelar: 'Cancelar',
  voltar: 'Voltar',
  publicado: 'Publicado',
  rascunho: 'Rascunho',
  publicar: 'Publicar',
  despublicar: 'Tirar do ar',
  subir: 'Subir',
  descer: 'Descer',
  editar: 'Editar',
  temas: {
    titulo: 'Temas',
    pagina: 'Conteúdo da comunidade',
    coluna: 'Tema',
    publicados: 'Temas publicados',
    aulasPublicadas: 'Aulas publicadas',
    aulasRascunho: 'Aulas em rascunho',
    novo: 'Novo tema',
    vazio: 'Nenhum tema ainda.',
    campoTitulo: 'Nome do tema',
    campoDescricao: 'Descrição',
  },
  etapas: {
    titulo: 'Etapas',
    nova: 'Nova etapa',
    vazio: 'Nenhuma etapa neste tema.',
    campoTitulo: 'Nome da etapa',
    campoDescricao: 'Descrição',
  },
  aulas: {
    titulo: 'Aulas',
    nova: 'Nova aula',
    editar: 'Editar aula',
    vazio: 'Nenhuma aula nesta etapa.',
    campoTitulo: 'Título da aula',
    campoDescricao: 'Descrição',
    campoVideo: 'Link do vídeo',
    exemploVideo: 'Cole o link do vídeo',
    semPrevia: 'Não foi possível mostrar a prévia desse link.',
    campoMaterial: 'Link do material (opcional)',
    campoProfissional: 'Profissional (opcional)',
    exemploProfissional: 'Ana, Clara ou Laís',
    campoDuracao: 'Duração em minutos (opcional)',
    liberacao: 'Quando libera',
    naCompra: 'Liberada na compra',
    seteDias: 'Depois de 7 dias',
    outroDia: 'Outro dia',
    campoDia: 'Dia de liberação',
    dia: (n: number) => (n === 1 ? 'Na compra' : n === 8 ? 'Após 7 dias' : `Dia ${n}`),
  },
  lives: {
    titulo: 'Lives',
    pagina: 'Lives da comunidade',
    coluna: 'Live',
    colunaData: 'Data',
    proxima: 'Próxima live',
    nenhuma: 'Nenhuma',
    agendadas: 'Lives agendadas',
    convidada: 'Convidada',
    nova: 'Nova live',
    editar: 'Editar live',
    vazio: 'Nenhuma live ainda.',
    campoTema: 'Tema da live',
    campoData: 'Data e hora',
    campoConvidada: 'Convidada (opcional)',
    campoLink: 'Link da live (opcional)',
    campoGravacao: 'Link da gravação (opcional)',
  },
  avisos: {
    titulo: 'Avisos',
    pagina: 'Avisos da comunidade',
    coluna: 'Aviso',
    colunaData: 'Aparece em',
    ativos: 'Avisos ativos',
    novo: 'Novo aviso',
    editar: 'Editar aviso',
    vazio: 'Nenhum aviso ainda.',
    campoTitulo: 'Título',
    campoTexto: 'Texto',
    campoPublicarEm: 'Aparece a partir de',
  },
  erros: {
    titulo: 'Escreva o título',
    link: 'Use um link que comece com https://',
    data: 'Escolha a data e a hora',
    dia: 'Use um dia de 1 em diante',
    texto: 'Escreva o texto',
    duracao: 'Use minutos inteiros, de 1 a 999',
  },
}
