// Textos da tela Equipe (Configurações). Os componentes só leem daqui.

export const t = {
  titulo: 'Equipe',
  convidar: 'Convidar profissional',
  cartoes: { ativas: 'Profissionais com acesso', pendentes: 'Convites pendentes' },
  colunas: ['Profissional', 'E-mail', 'Especialidade', 'Situação', ''],
  ativa: 'Ativa',
  pendente: 'Convite pendente',
  voce: 'você',
  nunca: 'Nunca entrou',
  ultimoAcesso: (d: string) => `Último acesso ${d}`,
  editar: 'Editar',
  gerarLink: 'Gerar link de acesso',
  tirarAcesso: 'Tirar acesso',
  confirmarTirar: (nome: string) => `Tirar o acesso de ${nome} ao painel?`,
  campos: {
    nome: 'Nome',
    email: 'E-mail',
    especialidade: 'Especialidade',
    nenhuma: 'Nenhuma',
    titulo: 'Título (ex.: Nutricionista)',
  },
  linkTitulo: 'Link de acesso',
  linkPronto: (nome: string) => `Envie este link para ${nome}. Ele vale uma vez.`,
  copiar: 'Copiar link',
  copiado: 'Link copiado',
  erros: {
    nome: 'Escreva o nome',
    email: 'Confira o e-mail',
    ja_existe: 'Este e-mail já tem conta na ORA.',
    falha: 'Não foi possível concluir. Tente de novo.',
  },
  voltar: 'Voltar para Configurações',
  vazio: 'Nenhuma profissional na equipe.',
  cancelar: 'Cancelar',
  salvar: 'Salvar',
  salvando: 'Salvando',
  fechar: 'Fechar',
}
