// Textos do fórum da aluna. Os componentes só leem daqui.

export const textos = {
  titulo: 'Fórum',
  daAula: 'Dúvidas desta aula',
  enviar: 'Enviar dúvida',
  tenhoDuvida: 'Tenho uma dúvida',
  enviando: 'Enviando',
  prazo: 'As profissionais respondem em até 72 horas.',
  campoDuvida: 'Sua dúvida',
  campoCategoria: 'Categoria',
  erroTexto: 'Escreva a dúvida com pelo menos 3 letras',
  erroLimite: 'Você já enviou 10 dúvidas hoje. Tente amanhã.',
  erroEnviar: 'Não foi possível enviar. Tente de novo.',
  buscar: 'Buscar no fórum',
  todas: 'Todas as categorias',
  minhas: 'Minhas dúvidas',
  geral: 'Geral',
  respostas: (n: number) => (n === 0 ? 'Sem respostas' : n === 1 ? '1 resposta' : `${n} respostas`),
  vazioAula: 'Nenhuma dúvida nesta aula ainda.',
  vazio: 'Nenhuma dúvida encontrada.',
  verMais: 'Ver mais',
  abrir: (texto: string) => `Abrir dúvida: ${texto}`,
  aguardando: 'Aguardando a resposta das profissionais',
  respondida: 'Respondida',
  responder: 'Responder',
  suaResposta: 'Sua resposta',
  erroResposta: 'Escreva a resposta',
  util: 'Resposta útil',
  curtir: (n: number) => `Curtir (${n})`,
  curtida: (n: number) => `Curtida (${n})`,
  denunciar: 'Denunciar',
  denunciada: 'Denúncia enviada',
  denunciarTitulo: 'Denunciar post',
  motivo: 'Motivo (opcional)',
  cancelar: 'Cancelar',
  fechar: 'Fechar',
  voltar: 'Voltar para o fórum',
  naoEncontrada: 'Esta dúvida não está disponível.',
  regras: {
    titulo: 'Regras do fórum',
    itens: [
      'Respeito sempre: aqui todas estão aprendendo juntas.',
      'Sem diagnóstico ou prescrição entre alunas. Dieta, remédio e treino individual ficam com as profissionais.',
      'Sem venda e sem divulgação de produtos, perfis ou serviços.',
    ],
    entendi: 'Entendi',
  },
  aviso: { titulo: 'Sua dúvida foi respondida', ver: 'Ver resposta' },
}
