// Textos do módulo Fórum do painel. Os componentes só leem daqui.

export const t = {
  titulo: 'Fórum',
  cartoes: {
    abertas: 'Dúvidas abertas',
    perto: 'Perto de vencer (menos de 12 h)',
    vencidas: 'Vencidas',
    semana: 'Respondidas na semana',
  },
  abas: { fila: 'Fila de dúvidas', denuncias: 'Denúncias' },
  colunas: ['Aluna', 'Dúvida', 'Aula', 'Categoria', 'Prazo'],
  geral: 'Geral',
  categoria: 'Categoria',
  aula: 'Aula',
  situacao: 'Situação',
  todas: 'Todas',
  situacoes: { abertas: 'Abertas', respondidas: 'Respondidas', ocultas: 'Ocultas' },
  paraMim: 'Para mim',
  respondida: 'Respondida',
  oculta: 'Oculta',
  vazio: 'Nenhuma dúvida neste filtro.',
  voltar: 'Voltar para a fila',
  abrirAula: 'Abrir aula',
  responder: 'Responder',
  suaResposta: 'Sua resposta',
  util: 'Marcar como útil',
  marcadaUtil: 'Marcada como útil',
  ocultar: 'Ocultar',
  ocultarTitulo: 'Ocultar post',
  motivo: 'Motivo',
  erroMotivo: 'Escreva o motivo',
  manter: 'Manter',
  denunciasVazio: 'Nenhuma denúncia aberta.',
  colunasDenuncias: ['Post', 'Autora', 'Denúncias', 'Último aviso', ''],
  tipoPost: (resposta: boolean) => (resposta ? 'Resposta' : 'Dúvida'),
  verConversa: 'Ver conversa',
  ocultaEm: (motivo: string | null) => `Oculta${motivo ? `: ${motivo}` : ''}`,
  meuPerfil: 'Meu perfil',
  perfil: {
    titulo: 'Meu perfil no fórum',
    nome: 'Nome que as alunas veem',
    especialidade: 'Especialidade',
    nenhuma: 'Nenhuma',
    tituloProf: 'Título (ex.: Nutricionista)',
    foto: 'Foto',
    trocarFoto: 'Escolher foto',
    erroNome: 'Escreva o nome',
    erroFoto: 'Use uma foto JPG, PNG ou WEBP de até 3 MB',
  },
  cancelar: 'Cancelar',
  salvar: 'Salvar',
  salvando: 'Salvando',
  fechar: 'Fechar',
  erro: 'Não foi possível salvar. Tente de novo.',
}
