// Textos dos desafios da aluna. Os componentes só leem daqui.

export const textos = {
  titulo: 'Desafios',
  abas: { mes: 'Do mês', encerrados: 'Encerrados' },
  abasRotulo: 'Quais desafios ver',
  carregando: 'Carregando os desafios',
  erro: 'Não foi possível carregar os desafios.',
  tentar: 'Tentar de novo',
  vazio: 'Nenhum desafio aberto agora. Assim que as profissionais lançarem um, ele aparece aqui.',
  vazioEncerrados: 'Os desafios de que você participar aparecem aqui quando terminarem.',
  naoEncontrado: 'Este desafio não está disponível.',
  voltar: 'Voltar para os desafios',
  participando: 'Participando',
  entrar: 'Entrar',
  entrarNoDesafio: 'Entrar no desafio',
  entrando: 'Entrando',
  periodo: (de: string, ate: string) => `${de} a ${ate}`,
  participantes: (n: number) => (n === 1 ? '1 participante' : `${n} participantes`),
  surpresa: 'Caixa surpresa',
  premio: 'Prêmio',
  meta: 'Meta',
  pontosRotulo: 'Pontos',
  regras: 'Como funciona',
  metaTexto: (dias: number, total: number) => `Completar ${dias} de ${total} dias`,
  porDia: 'Por dia',
  metaDiaria: (n: number, unidade: string) => `${n} ${unidade}`,
  pontosDia: (n: number, bonus: number) =>
    bonus > 0 ? `${n} pts por dia e ${bonus} de bônus ao completar` : `${n} pts por dia`,
  progresso: (dia: number, total: number, falta: number) =>
    falta > 0
      ? `Dia ${dia} de ${total} · faltam ${falta} para o prêmio`
      : `Dia ${dia} de ${total} · meta cumprida`,
  progressoRotulo: 'Progresso do desafio',
  calendario: 'Calendário do desafio',
  diaFeito: (d: string) => `${d}: feito`,
  diaHoje: (d: string) => `${d}: hoje`,
  diaVazio: (d: string) => d,
  comecaEm: (d: string) => `Começa em ${d}`,
  checkin: {
    titulo: 'Check-in de hoje',
    simNao: 'Fiz hoje',
    numero: (unidade: string) => `Quantos ${unidade} hoje?`,
    registrar: 'Registrar',
    foto: 'Tirar ou escolher foto',
    enviar: 'Enviar foto',
    enviando: 'Enviando',
    feito: 'Feito hoje',
    abaixo: (meta: number, unidade: string) =>
      `Registrado. O dia conta a partir de ${meta} ${unidade}.`,
    privado: 'Só você e as profissionais veem a foto.',
    erro: 'Não deu certo agora. Tente de novo.',
    numeroInvalido: 'Digite um número.',
  },
  ranking: 'Ranking do desafio',
  dias: (n: number, meta: number) => `${n}/${meta}`,
  semRanking: 'Ninguém entrou ainda. Seja a primeira.',
  encerrado: {
    completou: (feitos: number, meta: number) => `Você completou ${feitos} de ${meta} dias`,
    vencedoras: 'Vencedoras',
    ninguem: 'Ninguém completou desta vez.',
    voce: 'Você completou o desafio',
  },
  inicio: { ver: 'Ver desafio' },
}
